# Generated by Django 4.2.6 on 2023-11-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenditures", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expenditure",
            old_name="payment",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="expenditure",
            old_name="appropriate_payment",
            new_name="appropriate_amount",
        ),
    ]
