# Generated by Django 4.2.6 on 2023-11-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=("user", "category"), name="unique_user_category"
            ),
        ),
    ]
